package com.lipodico.inv.entities;
// Generated 30-12-2018 07:28:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Brands generated by hbm2java
 */
@Entity
@Table(name="brands"
    ,catalog="inventario"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Brands  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Date createdAt;
     private Set<Parts> partses = new HashSet<Parts>(0);
     private Set<Cars> carses = new HashSet<Cars>(0);

    public Brands() {
    }

	
    public Brands(int id) {
        this.id = id;
       
    }
    
    public Brands(String name, Date createdAt) {
        this.name = name;
        this.createdAt = createdAt;
    }
    public Brands(String name, Date createdAt, Set<Parts> partses, Set<Cars> carses) {
       this.name = name;
       this.createdAt = createdAt;
       this.partses = partses;
       this.carses = carses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="brands")
    public Set<Parts> getPartses() {
        return this.partses;
    }
    
    public void setPartses(Set<Parts> partses) {
        this.partses = partses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="brands")
    public Set<Cars> getCarses() {
        return this.carses;
    }
    
    public void setCarses(Set<Cars> carses) {
        this.carses = carses;
    }




}


