package com.lipodico.inv.entities;
// Generated 30-12-2018 07:28:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Moves generated by hbm2java
 */
@Entity
@Table(name="moves"
    ,catalog="inventario"
)
public class Moves  implements java.io.Serializable {


     private int id;
     private Clients clients;
     private Parts parts;
     private TypeMoves typeMoves;
     private int quantity;
     private Date createdAt;

    public Moves() {
    }

    public Moves(int id, Clients clients, Parts parts, TypeMoves typeMoves, int quantity, Date createdAt) {
       this.id = id;
       this.clients = clients;
       this.parts = parts;
       this.typeMoves = typeMoves;
       this.quantity = quantity;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_clients", nullable=false)
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_parts", nullable=false)
    public Parts getParts() {
        return this.parts;
    }
    
    public void setParts(Parts parts) {
        this.parts = parts;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_move_types", nullable=false)
    public TypeMoves getTypeMoves() {
        return this.typeMoves;
    }
    
    public void setTypeMoves(TypeMoves typeMoves) {
        this.typeMoves = typeMoves;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=true, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

}


