package com.lipodico.inv.entities;
// Generated 30-12-2018 07:28:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parts generated by hbm2java
 */
@Entity
@Table(name="parts"
    ,catalog="inventario"
)
public class Parts  implements java.io.Serializable {


     private Integer id;
     private Brands brands;
     private String name;
     private int stock;
     private int stockMin;
     private int stockMax;
     private Date createdAt;
     private Set<Moves> moveses = new HashSet<Moves>(0);

    public Parts() {
    }
    
     public Parts(int id) {
        this.id = id;
    }

	
    public Parts(String name, int stock, int stockMin, int stockMax, Date createdAt) {
        this.name = name;
        this.stock = stock;
        this.stockMin = stockMin;
        this.stockMax = stockMax;
        this.createdAt = createdAt;
    }
    public Parts(Brands brands, String name, int stock, int stockMin, int stockMax, Date createdAt, Set<Moves> moveses) {
       this.brands = brands;
       this.name = name;
       this.stock = stock;
       this.stockMin = stockMin;
       this.stockMax = stockMax;
       this.createdAt = createdAt;
       this.moveses = moveses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_brands")
    public Brands getBrands() {
        return this.brands;
    }
    
    public void setBrands(Brands brands) {
        this.brands = brands;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="stock", nullable=false)
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }

    
    @Column(name="stock_min", nullable=false)
    public int getStockMin() {
        return this.stockMin;
    }
    
    public void setStockMin(int stockMin) {
        this.stockMin = stockMin;
    }

    
    @Column(name="stock_max", nullable=false)
    public int getStockMax() {
        return this.stockMax;
    }
    
    public void setStockMax(int stockMax) {
        this.stockMax = stockMax;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="parts")
    public Set<Moves> getMoveses() {
        return this.moveses;
    }
    
    public void setMoveses(Set<Moves> moveses) {
        this.moveses = moveses;
    }




}


